# Site settings
author: Chris Baum
title: Chris Baum's Software Engineering Blog
header-img: img/home-bg.png
email: christopher.baum@valpo.edu
copyright_name: Chris Baum
description: > # this means to ignore newlines until "baseurl:"
  Blog about Software Engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ChrisBaum89

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
